export const spaces = [
       {
        "height":48,
        "id":98,
        "name":"start",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":0
               }],
        "rotation":0,
        "text":
           {
            "color":"#ff0000",
            "fontfamily":"Unifont",
            "halign":"center",
            "italic":true,
            "pixelsize":47,
            "text":"Start",
            "valign":"center",
            "wrap":true
           },
        "type":"",
        "visible":true,
        "width":140,
        "x":30.4242,
        "y":67.4394
       },
       {
        "gid":175,
        "height":64,
        "id":248,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":1
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":514,
        "y":130
       },
       {
        "gid":175,
        "height":64,
        "id":249,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":2
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":514,
        "y":238
       },
       {
        "gid":175,
        "height":64,
        "id":250,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":3
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":138,
        "y":272
       },
       {
        "gid":175,
        "height":64,
        "id":251,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":4
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":154,
        "y":424
       },
       {
        "gid":175,
        "height":64,
        "id":252,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":5
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":628,
        "y":454
       },
       {
        "gid":175,
        "height":64,
        "id":253,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":6
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":636,
        "y":84
       },
       {
        "gid":175,
        "height":64,
        "id":254,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":7
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":1014,
        "y":70
       },
       {
        "gid":175,
        "height":64,
        "id":255,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":8
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":1012,
        "y":176
       },
       {
        "gid":175,
        "height":64,
        "id":256,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":9
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":770,
        "y":208
       },
       {
        "gid":175,
        "height":64,
        "id":257,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":10
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":780,
        "y":324
       },
       {
        "gid":175,
        "height":64,
        "id":258,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":11
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":1142,
        "y":330
       },
       {
        "gid":175,
        "height":64,
        "id":259,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":12
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":1140,
        "y":634
       },
       {
        "gid":175,
        "height":64,
        "id":260,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":13
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":816,
        "y":644
       },
       {
        "gid":175,
        "height":64,
        "id":261,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":14
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":560,
        "y":646
       },
       {
        "gid":175,
        "height":64,
        "id":262,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":15
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":192,
        "y":658
       },
       {
        "gid":175,
        "height":64,
        "id":263,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":16
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":196,
        "y":884
       },
       {
        "gid":175,
        "height":64,
        "id":264,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":17
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":470,
        "y":890
       },
       {
        "gid":175,
        "height":64,
        "id":265,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":18
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":938,
        "y":888
       },
       {
        "gid":175,
        "height":64,
        "id":266,
        "name":"space",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":19
               }],
        "rotation":0,
        "type":"",
        "visible":true,
        "width":64,
        "x":958,
        "y":766
       },
       {
        "height":48,
        "id":124,
        "name":"start",
        "properties":[
               {
                "name":"position",
                "type":"int",
                "value":20
               }],
        "rotation":0,
        "text":
           {
            "color":"#ff0000",
            "fontfamily":"Unifont",
            "halign":"center",
            "italic":true,
            "pixelsize":47,
            "text":"Goal",
            "valign":"center",
            "wrap":true
           },
        "type":"",
        "visible":true,
        "width":140,
        "x":1121.33,
        "y":782.591
       }
   ]